consensus:
  enabled: true
  url: "http://localhost:5053"
  name: "consensus-client"
execution:
  enabled: true
  url: "http://localhost:8545"
  name: "execution-client"
  modules:
    - "eth"
    - "net"
    - "web3"
    - "txpool"
diskUsage:
  enabled: false
  interval: 30m
  directories:
  - /data/ethereum